# templates/external-dns-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: netflix-app
  labels:
    app: netflix-app
  annotations:
    external-dns.alpha.kubernetes.io/hostname: {{ .Values.externalDNS.hostname }}
spec:
  type: NodePort
  selector:
    app: netflix-app
  ports:
    - port: 80
      targetPort: 80
