---
apiVersion: v1
kind: Service
metadata:
  name: netflix-app
  labels:
    app: netflix-app
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30007
  selector:
    app: netflix-app

---
# apiVersion: v1
# kind: Service
# metadata:
#   name: netflix-app
#   namespace: default
# spec:
#   selector:
#     app: netflix-app
#   type: LoadBalancer
#   sessionAffinity: None
#   sessionAffinityConfig:
#     clientIP:
#       timeoutSeconds: 10800
#   ports:
#   - name: netflix-app
#     protocol: TCP
#     port: 8282 # Specify the port you want to use
#     targetPort: 80  # Specify the target port for your application
